# Run following command to run this container.
# Oracle database 23ai free
# docker compose -f Oracle23ai-Compose.yml up -d
#version: "3.8"
name: oracle23aidbcompose
services:
  oracle-db:
    container_name: oracle23aidev
    image: container-registry.oracle.com/database/free:latest
    environment:
      #- ORACLE_SID=ORCL
      - ORACLE_PDB=FREEPDB1
      - ORACLE_PWD=!MoinMoin015
    ports:
      - 1521:1521
      - 5501:5500
      #- 8080:8080
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test:
        [
          "CMD",
          "sqlplus",
          "-L",
          "sys/!MoinMoin015@//localhost:1521/FREEPDB1 as sysdba",
          "@healthcheck.sql",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  oracle-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: D:\DockerShared\OracleDBs\Oracle23aiDev\oradata
      o: bind
  oracle-backup:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: D:\DockerShared\OracleDBs\Oracle23aiDev\backup
      o: bind
