# Run following command to run this container.
# docker compose -f MySQLDBWithPhpAdminPortalCompose.yml up -d
#version: "3.8"
name: MySQLDBWithPhpAdminPortal
services:
  MySQLDBDev:
    container_name: MySQLDB
    image: mysql:latest    
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "!SaR00tAdmin"
      MYSQL_DATABASE: "northwind"
      MYSQL_USER: sa
      MYSQL_PASSWORD: "!MoinMoin015"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./NorthwindMySQL5.sql:/docker-entrypoint-initdb.d/NorthwindMySQL5.sql
    #  - ./db/my.cnf:/etc/mysql/my.cnf
    networks:
      - mysqldb_default
  phpmyadmin:
    depends_on:
      - MySQLDBDev
    container_name: phymyadminportal
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - "8090:80"
    environment:
      PMA_HOST: MySQLDBDev
      MYSQL_ROOT_PASSWORD: "!SaR00tAdmin"
    networks:
      - mysqldb_default
volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: D:\DockerShared\MySQL\MySQLDev1
      o: bind
networks:
  mysqldb_default:
    driver: bridge
